environment:
  # For new releases, only one job will upload the source code to Pypi, and only
  # one job each for Python 2 and 3 will upload a wheel.
  matrix:
    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      PYPI_UPLOAD_SOURCE: yes
      PYPI_UPLOAD_WHEEL: yes
      platform: x86

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      PYPI_UPLOAD_SOURCE: yes
      PYPI_UPLOAD_WHEEL: yes
      platform: x64

    - PYTHON: "C:\\Miniconda35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      PYPI_UPLOAD_SOURCE: yes
      PYPI_UPLOAD_WHEEL: yes
      platform: x86

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      PYPI_UPLOAD_SOURCE: no
      PYPI_UPLOAD_WHEEL: no
      platform: x64

    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      PYPI_UPLOAD_SOURCE: no
      PYPI_UPLOAD_WHEEL: yes
      platform: x86

    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      PYPI_UPLOAD_SOURCE: no
      PYPI_UPLOAD_WHEEL: no
      platform: x64

  ANACONDA_TOKEN:
    secure: 7drSxrQivCMViVHFeeFsfVzN3mELF6vkv4JAcuzdNedzFOvX1HAcGBTe0WolTsUJ

  TWINE_PASSWORD:
    secure: 4XvRpVVtji8vNnPGP2FUPQ==

install:
  # Add the paths for anaconda
  - 'set PATH=%PYTHON%;%PYTHON%\Library\bin;%PYTHON%\Scripts;%PATH%'
  # Install MPI
  - ps: (new-object net.webclient).DownloadFile(
        "https://download.microsoft.com/download/D/7/B/D7BBA00F-71B7-436B-80BC-4D22F2EE9862/MSMpiSetup.exe",
        "C:\projects\MSMpiSetup.exe")
  - C:\projects\MSMpiSetup.exe -unattend -minimal
  - set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
  # Check that we have the expected version and architecture for Python
  - 'python --version'
  - 'python -c "import struct; print(struct.calcsize(''P'') * 8)"'

build: false  # not a C# project

test_script:
  - conda install --yes --quiet -c conda-forge conda-build
  - conda build -c spyking-circus -c conda-forge conda_recipe
  - python packaging_tools/move_conda_package.py
  - conda install --yes --quiet wheel
  - python setup.py sdist --formats=zip,gztar,bztar
  - python setup.py bdist_wheel
  # Try installing from the source package (install dependencies via conda first)
  - conda install --yes --quiet -c spyking-circus -c conda-forge "tqdm!=4.15" mpi4py numpy cython scipy matplotlib h5py colorama psutil "qt>=4,<5"
  - FOR /R dist %%F in (*.tar.gz) do pip install %%F
  - spyking-circus -h
  - pip uninstall -y -q spyking-circus
  # Try installing from the binary wheel
  - FOR /R dist %%F in (*.whl) do pip install %%F
  - spyking-circus -h

after_test:
  - 'if "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" if "%APPVEYOR_REPO_NAME%" == "spyking-circus/spyking-circus" if "%APPVEYOR_REPO_TAG%" == "true" (
      conda install --yes --quiet anaconda-client &&
      conda install --yes --quiet -c conda-forge twine &&
      python packaging_tools\conda-server-push.py %APPVEYOR_REPO_TAG_NAME%
     )'
  - 'if "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" if "%APPVEYOR_REPO_NAME%" == "spyking-circus/spyking-circus" if "%APPVEYOR_REPO_TAG%" == "true" if "%PYPI_UPLOAD_SOURCE%" == "yes" (twine upload -u pierre.yger --skip-existing dist/*.tar.bz2)'
  - 'if "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" if "%APPVEYOR_REPO_NAME%" == "spyking-circus/spyking-circus" if "%APPVEYOR_REPO_TAG%" == "true" if "%PYPI_UPLOAD_WHEEL%" == "yes" (twine upload -u pierre.yger --skip-existing dist/*.whl)'

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: '*.tar.bz2'
    name: conda package
  - path: dist\*
    name: PyPI binaries
  